version: '3.1'
services:
    resources-mariadb:
        container_name: resources-mariadb
        image: mariadb:10
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_HOST=%
            - TZ=Asia/Seoul
        ports:
            - "13306:3306"
        volumes:
            - ./mariadb-init.d:/docker-entrypoint-initdb.d

    resources-adminer: # mysql web admin
        container_name: resources-adminer
        image: adminer:4
        ports:
            - "18080:8080"
        environment:
            - ADMINER_DEFAULT_SERVER=resources-mariadb
            - ADMINER_DESIGN=nette
            - ADMINER_PLUGINS=tables-filter tinymce

    resources-redis:
        image: redis:latest
        container_name: resources-redis
        ports:
            - "26379:6379"

    resources-redis-insight: # redis web admin
        image: redislabs/redisinsight:latest
        container_name: resources-redis-insight
        ports:
            - "18081:5540"

    resources-vault:
        image: hashicorp/vault:1.14.0
        container_name: resources-vault
        ports:
            - "18200:8200"
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: root
            VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
        cap_add:
            - IPC_LOCK
        command: vault server -dev

    resources-vault-init: # vault init
        image: hashicorp/vault:1.14.0
        container_name: resources-vault-init
        depends_on:
            - resources-vault
        entrypoint: [ "/bin/sh", "-c", "chmod +x /vault/init.sh && /vault/init.sh" ]
        volumes:
            - ./vault/data:/vault/data
            - ./vault/init.sh:/vault/init.sh